version: '3.8'

services:
  app:
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "2323:2323"
    restart: always
    command: >
      sh -c "
      npm i -g pnpm &&
      pnpm install &&
      pnpm build &&
      pnpm add start
      "